
services:
  ngrok:
    build: ngrok
    ports:
      # expose ngrok client interface to host
      - 4040:4040
    depends_on:
      - wxc_cc_bot
    # redirect traffic to event_monitor service
    # command: http event_monitor:6001 --log stderr --log-level debug
    command: http wxc_cc_bot:6001

  redis:
      image: redis:alpine
      ports:
        - 6379:6379
      volumes:
        - .:/data
      command: redis-server --save 60 1

  wxc_cc_bot:
    build: .
    ports:
      # need to expose port 6001 to allow direct GET from local browser at end of auth flow
      - 6001:6001
    environment:
      # inform bot of ngrok instance
      - NGROK_HOST=ngrok
      - REDIS_HOST=redis
    command: gunicorn 'wxc_cc_bot:create_app()' --workers=1 -b :6001
